inputs_def:
  - handle: txt_file
    description: "%path-to-the-txt-file-to-read%"
    json_schema:
      type: string
      ui:widget: file
    nullable: false

outputs_def:
  - handle: first_800_chars
    description: "%first-800-characters-extracted-from-the-file%"
    json_schema:
      type: string
  - handle: filename
    description: "%base-name-of-the-input-file-without-path%"
    json_schema:
      type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "%extract-first-800-characters%"
icon: ":carbon:text-creation:"
description: "%extracts-the-first-800-characters-from-a-txt-file-and-returns-th%"
private: true
